version: "3.4"

services:
  gasrush:
    image: gasrush
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    ports: ["3000:3000"]
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017

  mongodb:
    image: mongo
    restart: always
    volumes:
      - ~/mongo:/data/db
    ports: ["27017:27017"]
volumes:
  mongo_data:
